"""
Django settings for bookmyseat project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import sys
import dj_database_url
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Reads from env first; falls back to the provided production key so Vercel runs even if env vars are missing.
SECRET_KEY = os.environ.get('SECRET_KEY')
# Default to a dummy key if missing to avoid crashing the invocation immediately
if not SECRET_KEY:
    SECRET_KEY = 'django-insecure-fallback-key-for-initial-deployment'

# SECURITY WARNING: don't run with debug turned on in production!
# Default to debug-on for local runs; set DJANGO_DEBUG=false in production.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ['.vercel.app', 'localhost', '127.0.0.1']
CSRF_TRUSTED_ORIGINS = ['https://*.vercel.app']

# This is required for Django to correctly identify that the request is secure (HTTPS)
# when running behind Vercel's proxy. Without this, Login/Register POST requests
# will likely fail with a 403 CSRF error.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',
    'movies.apps.MoviesConfig',
    'experiences.apps.ExperiencesConfig',
    'analytics.apps.AnalyticsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL='auth.User'
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "2525"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() == "true"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "false").lower() == "true"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "no-reply@example.com")
EMAIL_TIMEOUT = 10  # Seconds to wait for SMTP server response

# If secure SMTP settings are provided, switch backend automatically.
if EMAIL_HOST:
    EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")

# Stripe Payment Settings
STRIPE_PUBLIC_KEY = os.getenv("STRIPE_PUBLIC_KEY", "").strip()
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "").strip()
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "").strip()
STRIPE_CURRENCY = os.getenv("STRIPE_CURRENCY", "INR").strip() or "INR"
try:
    TICKET_PRICE = float(os.getenv("TICKET_PRICE", "250.00"))  # Price per ticket in INR
except ValueError:
    TICKET_PRICE = 250.00

SEAT_HOLD_MINUTES = int(os.getenv("SEAT_HOLD_MINUTES", "2"))
RESERVATION_CLEANUP_INTERVAL_SECONDS = int(os.getenv("RESERVATION_CLEANUP_INTERVAL_SECONDS", "30"))

# CRITICAL: Disable Background Scheduler on Vercel as serverless functions don't support persistent threads
ENABLE_BACKGROUND_SCHEDULER = os.getenv("ENABLE_BACKGROUND_SCHEDULER", "false" if not DEBUG else "true").lower() == "true"

YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY", "").strip()
# Base URL used to embed YouTube trailers. Some environments/browsers can be picky
# about the domain; allow override via env.
# Examples:
# - https://www.youtube-nocookie.com/embed/  (default, privacy-friendly)
# - https://www.youtube.com/embed/
YOUTUBE_EMBED_BASE = os.getenv(
    "YOUTUBE_EMBED_BASE", "https://www.youtube-nocookie.com/embed/"
).strip()

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


ROOT_URLCONF = 'bookmyseat.urls'
LOGIN_URL='/login/'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookmyseat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL')
RUNNING_TESTS = 'test' in sys.argv

# Ensures a valid remote URL is used (contains ://) and not during tests.
use_remote_db = DATABASE_URL and '://' in DATABASE_URL and not RUNNING_TESTS

if use_remote_db:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=int(os.environ.get('CONN_MAX_AGE', 0)),
            # Ensure SSL is required for Supabase
            ssl_require=os.environ.get('POSTGRES_REQUIRE_SSL', 'True').lower() == 'true',
        )
    }
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
    # PgBouncer/Supabase optimizations and cleanup
    db_config = DATABASES['default']
    options = db_config.setdefault('OPTIONS', {})

    # Remove 'pgbouncer' from options as psycopg2 rejects unknown connection parameters
    options.pop('pgbouncer', None)

    options.update({
        'options': '-c search_path=public',
        'connect_timeout': 10,
    })
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Use CompressedStaticFilesStorage to avoid startup crashes if the manifest is missing
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Caching Configuration
REDIS_URL = os.environ.get('REDIS_URL')
if REDIS_URL and REDIS_URL.startswith('redis://'):
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.environ.get('REDIS_URL'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }

# Cache timeout for analytics (24 hours)
ANALYTICS_CACHE_TIMEOUT = 86400

# Minimal logging so email queue failures are visible in ops logs.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '%(levelname)s %(name)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        # Surface email sending failures and queue processing issues.
        'movies.management.commands.process_email_queue': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Lightweight perf logging for hot endpoints (e.g., movie list).
        'movies.perf': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
