# Generated by Django 3.2.19 on 2026-04-22 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=32)),
                ('booked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('template', models.CharField(max_length=255)),
                ('context', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('scheduled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(choices=[('event', 'Event'), ('premiere', 'Premiere'), ('music_studio', 'Music Studio')], db_index=True, max_length=32)),
                ('image', models.ImageField(blank=True, null=True, upload_to='experiences/')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('trailer_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='experiences.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('address', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=250.0, max_digits=9)),
                ('seat_map_enabled', models.BooleanField(default=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='experiences.experience')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='experiences.venue')),
            ],
            options={
                'ordering': ['start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='experiences.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_seat_reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='experiences.session'),
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=128)),
                ('payload', models.BinaryField()),
                ('signature_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='experiences.payment')),
            ],
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['type', 'name'], name='experiences_type_3b528c_idx'),
        ),
        migrations.AddField(
            model_name='booking',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='experiences.experience'),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='experiences.seat'),
        ),
        migrations.AddField(
            model_name='booking',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='experiences.session'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['experience', 'start_time'], name='experiences_experie_7b24f3_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['venue', 'start_time'], name='experiences_venue_i_5e8e55_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['session', 'is_booked'], name='experiences_session_bc7c4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('session', 'seat_number')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentattempt',
            unique_together={('payment', 'stripe_event_id')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'booked_at'], name='experiences_user_id_f35cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment_id'], name='experiences_payment_892429_idx'),
        ),
    ]
