# Generated by Django 6.0.4 on 2026-06-10 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
        ('movies', '0016_alter_analyticscache_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='director',
            field=models.CharField(blank=True, help_text='Director or main performer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiences', to='movies.language'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['rating'], name='experiences_rating_d30928_idx'),
        ),
    ]
