# Generated by Django 5.2.11 on 2026-03-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_options_genre_movie_genres_language_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['language', 'name'], name='movies_movi_languag_9e3e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['name', 'id'], name='movies_movi_name_3573ca_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['rating', 'id'], name='movies_movi_rating_345343_idx'),
        ),
    ]
