# Generated by Django 5.2.11 on 2026-03-15 17:58

from django.db import migrations, models
import django.db.models.deletion


def create_default_language(apps, schema_editor):
    Language = apps.get_model("movies", "Language")
    Movie = apps.get_model("movies", "Movie")
    default_lang, _ = Language.objects.get_or_create(
        code="en", defaults={"name": "English"}
    )
    Movie.objects.filter(language__isnull=True).update(language=default_lang)


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_movies_movi_languag_9e3e5f_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_language, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='movies.language'),
        ),
    ]
