# Generated by Codex on 2026-03-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_ensure_language_defaults'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS movies_genre_movie_idx ON movies_movie_genres (genre_id, movie_id);",
            reverse_sql="DROP INDEX IF EXISTS movies_genre_movie_idx;",
        ),
    ]
