# Generated by Codex on 2026-03-24
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_genres_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64),
        ),
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('template', models.CharField(max_length=255)),
                ('context', models.JSONField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheduled_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='emailqueue',
            index=models.Index(fields=['status', 'scheduled_at'], name='movies_emai_status_2f565f_idx'),
        ),
    ]
