# Generated by Django 3.2.19 on 2026-03-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_email_queue_and_payment_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailqueue',
            name='movies_emai_status_2f565f_idx',
        ),
        migrations.AddIndex(
            model_name='emailqueue',
            index=models.Index(fields=['status', 'scheduled_at'], name='movies_emai_status_065111_idx'),
        ),
    ]
