# Generated by Django 5.2.11 on 2026-04-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_booking_status_payment_paymentattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='client_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
