# Generated by Django 3.2.19 on 2026-04-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_seat_reservation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='seatreservation',
            name='movies_seat_expires_8f3e4b_idx',
        ),
        migrations.RemoveIndex(
            model_name='seatreservation',
            name='movies_seat_seat_id_9f4b5c_idx',
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['expires_at'], name='movies_seat_expires_b885cc_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['seat', 'expires_at'], name='movies_seat_seat_id_f8e7be_idx'),
        ),
    ]
