# Generated by Django 6.0.4 on 2026-04-24 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20260424_1049'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('analytics_admin', 'Analytics Admin'), ('support_admin', 'Support Admin'), ('finance_admin', 'Finance Admin')], default='analytics_admin', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view_dashboard', 'Viewed Dashboard'), ('export_report', 'Exported Report'), ('download_data', 'Downloaded Data'), ('user_login', 'User Login'), ('settings_change', 'Settings Changed')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='movies.adminuser')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('cache_label', models.CharField(choices=[('daily_revenue', 'Daily Revenue'), ('weekly_revenue', 'Weekly Revenue'), ('monthly_revenue', 'Monthly Revenue'), ('popular_movies', 'Popular Movies'), ('theater_occupancy', 'Theater Occupancy'), ('popular_experiences', 'Popular Experiences'), ('venue_occupancy', 'Venue Occupancy'), ('peak_booking_hours', 'Peak Booking Hours'), ('cancellation_rate', 'Cancellation Rate')], default='daily_revenue', max_length=100)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='movies_anal_expires_b1f51b_idx'), models.Index(fields=['cache_key', 'expires_at'], name='movies_anal_cache_k_4056b2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['role', 'is_active'], name='movies_admi_role_bb572c_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['user', 'is_active'], name='movies_admi_user_id_85f8ab_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['admin_user', 'timestamp'], name='movies_admi_admin_u_7a9a35_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['action', 'timestamp'], name='movies_admi_action_a26ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivitylog',
            index=models.Index(fields=['timestamp'], name='movies_admi_timesta_18e13c_idx'),
        ),
    ]
