# Generated by Django 6.0.4 on 2026-06-10 15:40

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_booking_movies_book_status_5cd60b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticscache',
            name='data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
